# Generated by Django 5.2.12 on 2026-04-22 11:54

import apps.data_manage.models
import apps.version_pack.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCommonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('versions', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('common_property', models.FileField(max_length=256, storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.data_manage.models.common_property_path, verbose_name='通用资产')),
                ('property_desc', models.TextField(blank=True, null=True, verbose_name='资产说明')),
                ('property_tag', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimProjectProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('apply_project', models.CharField(max_length=64, verbose_name='适用项目')),
                ('project_property', models.FileField(max_length=256, storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.data_manage.models.project_property_path, verbose_name='项目资产')),
                ('property_desc', models.TextField(blank=True, null=True, verbose_name='资产说明')),
                ('property_tag', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签')),
                ('creator', models.CharField(max_length=16, verbose_name='创建人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
