# Generated by Django 5.2.12 on 2026-04-22 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcommonproperty',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
