# Generated by Django 5.2.12 on 2026-04-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0002_simcommonproperty_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simprojectproperty',
            name='creator',
        ),
    ]
