# Generated by Django 5.2.12 on 2026-04-20 12:19

import apps.version_pack.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('env_note', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('env_file', models.FileField(upload_to=apps.version_pack.models.per_env_path, verbose_name='环境文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'per_env',
                'unique_together': {('env_name',)},
            },
        ),
        migrations.CreateModel(
            name='PerVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_num', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('versions_type', models.JSONField(verbose_name='版本类型')),
                ('versions_file', models.FileField(max_length=256, storage=apps.version_pack.models.OverwriteStorage(), upload_to='', verbose_name='版本文件')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('dev_test_result', models.TextField(blank=True, null=True, verbose_name='研发提测')),
                ('database_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['db'])], verbose_name='数据库文件')),
                ('test_result', models.CharField(blank=True, choices=[('未开始', '未开始'), ('测试中', '测试中'), ('通过', '通过'), ('失败', '失败'), ('中断', '中断')], default='未开始', max_length=32, null=True, verbose_name='测试结果')),
                ('test_verdict', models.TextField(blank=True, null=True, verbose_name='测试总结')),
                ('version_file', models.FileField(storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.per_version_path, verbose_name='版本文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_pack.perenv', verbose_name='适用环境')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'per_version',
                'unique_together': {('version_num',)},
            },
        ),
    ]
