# Generated by Django 5.2.12 on 2026-04-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_pack', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perenv',
            unique_together=set(),
        ),
    ]
