# Generated by Django 5.2.12 on 2026-04-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_pack', '0002_alter_perenv_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='perversion',
            name='versions_file',
        ),
    ]
