# Generated by Django 5.2.12 on 2026-04-22 02:15

import apps.version_pack.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_pack', '0003_alter_perversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perversion',
            name='database_file',
            field=models.FileField(blank=True, null=True, storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.per_version_path, validators=[django.core.validators.FileExtensionValidator(['db'])], verbose_name='数据库文件'),
        ),
    ]
