# Generated by Django 5.2.12 on 2026-04-22 10:42

import apps.version_pack.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_pack', '0004_alter_perversion_database_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtlEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('env_note', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('env_file', models.FileField(upload_to=apps.version_pack.models.ctl_env_path, verbose_name='环境文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctl_env',
            },
        ),
        migrations.CreateModel(
            name='CtlVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_num', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('versions_type', models.JSONField(verbose_name='版本类型')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('dev_test_result', models.TextField(blank=True, null=True, verbose_name='研发提测')),
                ('test_result', models.CharField(blank=True, choices=[('未开始', '未开始'), ('测试中', '测试中'), ('通过', '通过'), ('失败', '失败'), ('中断', '中断')], default='未开始', max_length=32, null=True, verbose_name='测试结果')),
                ('test_verdict', models.TextField(blank=True, null=True, verbose_name='测试总结')),
                ('version_file', models.FileField(storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.ctl_version_path, verbose_name='版本文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_pack.ctlenv', verbose_name='适用环境')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctl_version',
            },
        ),
        migrations.CreateModel(
            name='LocEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('env_note', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('env_file', models.FileField(upload_to=apps.version_pack.models.loc_env_path, verbose_name='环境文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loc_env',
            },
        ),
        migrations.CreateModel(
            name='LocVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_num', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('versions_type', models.JSONField(verbose_name='版本类型')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('dev_test_result', models.TextField(blank=True, null=True, verbose_name='研发提测')),
                ('test_result', models.CharField(blank=True, choices=[('未开始', '未开始'), ('测试中', '测试中'), ('通过', '通过'), ('失败', '失败'), ('中断', '中断')], default='未开始', max_length=32, null=True, verbose_name='测试结果')),
                ('test_verdict', models.TextField(blank=True, null=True, verbose_name='测试总结')),
                ('version_file', models.FileField(storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.loc_version_path, verbose_name='版本文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_pack.locenv', verbose_name='适用环境')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loc_version',
            },
        ),
        migrations.CreateModel(
            name='SenEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('env_note', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('env_file', models.FileField(upload_to=apps.version_pack.models.sen_env_path, verbose_name='环境文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sen_env',
            },
        ),
        migrations.CreateModel(
            name='SenVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_num', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('versions_type', models.JSONField(verbose_name='版本类型')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('dev_test_result', models.TextField(blank=True, null=True, verbose_name='研发提测')),
                ('test_result', models.CharField(blank=True, choices=[('未开始', '未开始'), ('测试中', '测试中'), ('通过', '通过'), ('失败', '失败'), ('中断', '中断')], default='未开始', max_length=32, null=True, verbose_name='测试结果')),
                ('test_verdict', models.TextField(blank=True, null=True, verbose_name='测试总结')),
                ('version_file', models.FileField(storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.sen_version_path, verbose_name='版本文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_pack.senenv', verbose_name='适用环境')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sen_version',
            },
        ),
        migrations.CreateModel(
            name='SimEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_name', models.CharField(max_length=128, unique=True, verbose_name='环境名称')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('env_note', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('env_file', models.FileField(upload_to=apps.version_pack.models.sim_env_path, verbose_name='环境文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sim_env',
            },
        ),
        migrations.CreateModel(
            name='SimVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_num', models.CharField(max_length=128, unique=True, verbose_name='版本号')),
                ('versions_type', models.JSONField(verbose_name='版本类型')),
                ('apply_project', models.CharField(default='主线版本', max_length=16, verbose_name='适用专项')),
                ('dev_test_result', models.TextField(blank=True, null=True, verbose_name='研发提测')),
                ('test_result', models.CharField(blank=True, choices=[('未开始', '未开始'), ('测试中', '测试中'), ('通过', '通过'), ('失败', '失败'), ('中断', '中断')], default='未开始', max_length=32, null=True, verbose_name='测试结果')),
                ('test_verdict', models.TextField(blank=True, null=True, verbose_name='测试总结')),
                ('version_file', models.FileField(storage=apps.version_pack.models.OverwriteStorage(), upload_to=apps.version_pack.models.sim_version_path, verbose_name='版本文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_pack.simenv', verbose_name='适用环境')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sim_version',
            },
        ),
    ]
