# Generated by Django 5.2.12 on 2026-04-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_pack', '0005_ctlenv_ctlversion_locenv_locversion_senenv_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ctlenv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ctlversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locenv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='perenv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='perversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='senenv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='senversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='simenv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='simversion',
            table=None,
        ),
    ]
