"""
Django settings for dev_perceptionpro project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from config import perceptionpro_cfg as ppc
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# app 集合到 apps
sys.path.insert(0, os.path.join(BASE_DIR, 'apps')),

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s92*tg=kouy=_+^*0jn236l5ntyvda%jiq&($5+mhi&hh0r&b7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 三方
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'django_celery_results',
    'django_celery_beat',
    # 个人
    'apps.back_stage.apps.BackStageConfig',
    'apps.version_pack.apps.VersionPackConfig',
    'apps.data_manage.apps.DataManageConfig',
    'apps.sim_test_agv.apps.SimTestAgvConfig',
    'apps.sim_test_get.apps.SimTestGetConfig',
]

# REST_FRAMEWORK = {
#     # 过滤器默认后端
#     'DEFAULT_FILTER_BACKENDS': (
#         'django_filters.rest_framework.DjangoFilterBackend',),
#     'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.AutoSchema',
# }

REST_FRAMEWORK = {
    # 认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 权限
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # 过滤
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # 分页
    'DEFAULT_PAGINATION_CLASS': 'apps.common_views.response.CustomPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'EXCEPTION_HANDLER': 'apps.common_views.response.custom_exception_handler',

    "DEFAULT_RENDERER_CLASSES": [
        "apps.common_views.response.CustomJSONRenderer",
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,  # 每次 refresh 生成新 refresh token
    'BLACKLIST_AFTER_ROTATION': True,  # 防止旧 token 被重复使用
}

AUTHENTICATION_BACKENDS = [
    'apps.back_stage.authentication.PhoneBackend',  # 你的
    'django.contrib.auth.backends.ModelBackend',  # 保留默认（很重要）
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dev_perceptionpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev_perceptionpro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.mysql',
        "NAME": ppc.PER_DB_NAME,
        "USER": "root",
        "PASSWORD": "123456",
        "HOST": ppc.PER_DB_HOST,
        "PORT": 3306,
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # 指定缓存使用的引擎
        'LOCATION': 'unique-snowflake',  # 写在内存中的变量的唯一值
        'TIMEOUT': 300,  # 缓存超时时间(默认为300秒,None表示永不过期)
        'OPTIONS': {
            'MAX_ENTRIES': 300,  # 最大缓存记录的数量（默认300）
            'CULL_FREQUENCY': 3,  # 缓存到达最大个数之后，剔除缓存个数的比例，即：1/CULL_FREQUENCY（默认3）
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 语言
LANGUAGE_CODE = 'zh-Hans'

# 时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 静态文件路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_URL = 'static/'

# 生产环境 collectstatic 输出目录（开发时不生效）
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 存储文件路径
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

# 允许当前网址域名下嵌入内容
X_FRAME_OPTIONS = 'SAMEORIGIN'  # django 3.0 + 默认为 deny

# 控制是否允许跨域窗口的访问
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

DATA_UPLOAD_MAX_NUMBER_FILES = 200

# 是否重定向到以/结尾
# APPEND_SLASH = False

# ASGI 应用程序入口 处理 websocket 必选项
ASGI_APPLICATION = "per_test_platform.asgi.application"

# redis 配置
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

AUTH_USER_MODEL = 'back_stage.User'

CORS_ALLOW_ALL_ORIGINS = True

# ── 生产环境覆盖（local_settings.py 不被 git 追踪）────────────────────
try:
    from dev_perceptionpro.local_settings import *  # noqa
except ImportError:
    pass

# ── Logging ──────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'when': 'midnight',
            'backupCount': 30,          # 保留最近 30 天
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'audit_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'audit.log',
            'when': 'midnight',
            'backupCount': 90,          # 审计日志保留 90 天
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },

    'loggers': {
        # 审计日志（登录、增改删操作）
        'apps.audit': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 业务日志（apps.xxx 均继承此 logger）
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django 请求异常（4xx/5xx）
        'django.request': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 其余 django 内部日志只写 WARNING+
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
